# Generated by Django 5.2.3 on 2025-07-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=200)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
